### PR TITLE
I apoligze sincerely for the size 🙏

### PR DESCRIPTION
**Pull request by Chef-Baker**
Black and White texture pack that can't even make everything Black and White B)

### CODE REVIEW

**Comment by itzTheMeow** [comment]
me when
```js
document.body.style.filter="grayscale(1)"
```

**Comment by itzTheMeow** [comment]
L
image

**Comment by Chef-Baker** [comment]
> me when
> 
> ```js
> document.body.style.filter="grayscale(1)"
> ```

qhar

**Comment by itzTheMeow** [comment]
i'm... probably just going to make this a mod

**Pull request closed without merging**
