### PR TITLE
Star Wars

### PR DESCRIPTION
**Pull request by SniperBarrel**
Name changed, also Link Gun is supposed to be empty. Sorry but I don't use GitHub at all, so I didn't even know you can comment through it XD

### CODE REVIEW

**Comment by itzTheMeow** [comment]
what is the point in making a weapon transparent lmao, id prefer not

**Comment by itzTheMeow** [comment]
like the "transparent" pack is ok bc you know everything's transparent, but randomly putting a transparent texture in a normal pack could confuse people

**Comment by SniperBarrel** [comment]
> what is the point in making a weapon transparent lmao, id prefer not

Well, Palpatine didn't have to hold anything when he was decimating Mace Windu, right?...

**Comment by itzTheMeow** [comment]
ok nerd

**Pull request merged**
