### PR TITLE
Hotkeymessages

### PR DESCRIPTION
**Pull request by AnnaBanana2577**
Hi Meow,

Hotkey messages allow users to bind predefined messages to a select number of hotkeys, and then use said hotkeys in-game to instantly sent that message in chat.
hotkeymessages ss

### CODE REVIEW

**Comment by itzTheMeow** [comment]
poggers first content pr

**Comment by AnnaBanana2577** [comment]
I think my prettier config might show some noice on the commits lol

**Comment by itzTheMeow** [comment]
lmao i just DMed you about that

**Review by itzTheMeow — APPROVED** [review]
insane

**Pull request merged**
